<a href="https://colab.research.google.com/github/manishbhnau/Repo/blob/master/knn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
from google.colab import files
uploaded=files.upload()

Saving Credit.csv to Credit (2).csv


In [32]:
import pandas as pd
#read in the data using pandas
df = pd.read_csv("Credit.csv")
#check data has been read in properly
col=df.columns.tolist()
print (col)
print (df.head())
print (df.shape)

['Unnamed: 0', 'Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Gender', 'Student', 'Married', 'Ethnicity', 'Balance', 'Defaultee']
   Unnamed: 0   Income  Limit  Rating  ...  Married  Ethnicity  Balance Defaultee
0           1   14.891   3606     283  ...      Yes  Caucasian      333         0
1           2  106.025   6645     483  ...      Yes      Asian      903         0
2           3  104.593   7075     514  ...       No      Asian      580         0
3           4  148.924   9504     681  ...       No      Asian      964         0
4           5   55.882   4897     357  ...      Yes  Caucasian      331         0

[5 rows x 13 columns]
(400, 13)


In [33]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
df["Ethnicity_code"] = lb_make.fit_transform(df["Ethnicity"])
df["Student_code"] = lb_make.fit_transform(df["Student"])
df["Married_code"] = lb_make.fit_transform(df["Married"])
df["Cards_code"] = lb_make.fit_transform(df["Cards"])
df["Gender_code"] = lb_make.fit_transform(df["Gender"])

df[["Ethnicity", "Ethnicity_code", "Student", "Student_code", "Married", "Married_code", "Cards", "Cards_code", "Gender", "Gender_code"]].head(5)

Ethnicity  Ethnicity_code Student  ...  Cards_code  Gender  Gender_code
0  Caucasian               2      No  ...           1    Male            1
1      Asian               1     Yes  ...           2  Female            0
2      Asian               1      No  ...           3    Male            1
3      Asian               1      No  ...           2  Female            0
4  Caucasian               2      No  ...           1    Male            1

[5 rows x 10 columns]

In [49]:
y=df["Defaultee"].values; y=y.astype(int)
dftemp=df.drop(columns=["Defaultee", "Ethnicity", "Married", "Student", "Cards", "Gender"])
X=dftemp.values; X=X.astype(int)
print (X[:5], y[:5])

[[   1   14 3606  283   34   11  333    2    0    1    1    1]
 [   2  106 6645  483   82   15  903    1    1    1    2    0]
 [   3  104 7075  514   71   11  580    1    0    0    3    1]
 [   4  148 9504  681   36   11  964    1    0    0    2    0]
 [   5   55 4897  357   68   16  331    2    0    1    1    1]] [0 0 0 0 0]


In [52]:
from sklearn import preprocessing

x = dftemp.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
dftemp = pd.DataFrame(x_scaled)
print (dftemp)

           0         1         2         3   ...   8    9      10   11
0    0.000000  0.025737  0.210675  0.213723  ...  0.0  1.0  0.125  1.0
1    0.002506  0.542722  0.443406  0.438695  ...  1.0  1.0  0.250  0.0
2    0.005013  0.534598  0.476336  0.473566  ...  0.0  0.0  0.375  1.0
3    0.007519  0.786079  0.662353  0.661417  ...  0.0  0.0  0.250  0.0
4    0.010025  0.258271  0.309542  0.296963  ...  0.0  1.0  0.125  1.0
..        ...       ...       ...       ...  ...  ...  ...    ...  ...
395  0.989975  0.009882  0.248507  0.240720  ...  0.0  1.0  0.250  1.0
396  0.992481  0.017075  0.228442  0.228346  ...  0.0  0.0  0.500  1.0
397  0.994987  0.269560  0.253944  0.256468  ...  0.0  1.0  0.500  0.0
398  0.997494  0.155287  0.127891  0.111361  ...  0.0  1.0  0.000  1.0
399  1.000000  0.047351  0.357559  0.362205  ...  0.0  0.0  0.500  0.0

[400 rows x 12 columns]


In [53]:
y=df["Defaultee"].values; y=y.astype(int)
dftemp=df.drop(columns=["Defaultee", "Ethnicity", "Married", "Student", "Cards", "Gender"])
X=dftemp.values; X=X.astype(int)
print (X[:5], y[:5])

[[   1   14 3606  283   34   11  333    2    0    1    1    1]
 [   2  106 6645  483   82   15  903    1    1    1    2    0]
 [   3  104 7075  514   71   11  580    1    0    0    3    1]
 [   4  148 9504  681   36   11  964    1    0    0    2    0]
 [   5   55 4897  357   68   16  331    2    0    1    1    1]] [0 0 0 0 0]


In [54]:
from sklearn.model_selection import train_test_split
#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((320, 12), (320,), (80, 12), (80,))

## **KNN**

In [64]:
from sklearn.neighbors import KNeighborsClassifier
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 2)
# Fit the classifier to the data
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [65]:
#show first 5 model predictions on the test data
knn.predict(X_test)#[0:5]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

0.9625

## **k-Fold Cross-Validation**

In [58]:
from sklearn.model_selection import cross_val_score
import numpy as np
#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=2)
#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, X, y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))

[0.95   0.9625 0.9625 0.9625 0.95  ]
cv_scores mean:0.9574999999999999


In [ ]:
from sklearn.model_selection import KFold
#print (X.shape)
kf = KFold(n_splits=5)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

In [ ]:
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()
for train, test in loo.split(X):
    print("%s %s" % (train, test))

In [ ]:
from sklearn.model_selection import LeavePOut

lpo = LeavePOut(3)

for train_index, test_index in lpo.split(X[:10]):
    print("TRAIN:", train_index, "TEST:", test_index)
    #try:
    #  print("TRAIN:", train_index, "TEST:", test_index)
    #  #x_train, x_test = X_train[train_index], X_train[test_index]
    #  yy_train, yy_test = y_train[train_index], y_train[test_index]
    #except:
    #  pass
    #  #break

## **Hypertuning model parameters using GridSearchCV**

In [60]:
from sklearn.model_selection import GridSearchCV
#create new a knn model
knn2 = KNeighborsClassifier()
#create a dictionary of all values we want to test for n_neighbors
param_grid = {"n_neighbors": np.arange(1, 25)}
#use gridsearch to test all values for n_neighbors
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)
#fit model to data
knn_gscv.fit(X, y)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [66]:
#check top performing n_neighbors value
knn_gscv.best_params_

{'n_neighbors': 1}

In [62]:
#check mean score for the top performing value of n_neighbors
knn_gscv.best_score_

0.9675

In [63]:
print(knn_gscv.cv_results_)

{'mean_fit_time': array([0.00115247, 0.00066085, 0.00065098, 0.00064511, 0.00066986,
       0.000634  , 0.00060134, 0.00060616, 0.00062332, 0.00065117,
       0.00062594, 0.00063486, 0.00061069, 0.00067286, 0.00062728,
       0.00063014, 0.00066886, 0.00064378, 0.00062375, 0.00064139,
       0.00066586, 0.00069237, 0.00068736, 0.00071511]), 'std_fit_time': array([8.54004160e-04, 6.39686245e-05, 2.76136065e-05, 1.63231605e-05,
       3.67915018e-05, 1.37915617e-05, 1.45027496e-05, 1.71572609e-05,
       3.40274685e-05, 5.18268251e-05, 1.62549024e-05, 4.24576298e-05,
       8.11968416e-06, 7.21357702e-05, 5.30012599e-05, 2.34572866e-05,
       2.12466139e-05, 1.66267859e-05, 1.58682924e-05, 1.87684947e-05,
       4.89304168e-05, 2.38079784e-05, 7.00966841e-06, 9.85128259e-05]), 'mean_score_time': array([0.00388207, 0.00334821, 0.00313773, 0.00304346, 0.00319967,
       0.00304723, 0.00306201, 0.00302324, 0.00321126, 0.00303125,
       0.00310163, 0.00305061, 0.0030508 , 0.00319843, 0.003